version: "3.9"
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=murloc
    command: --default-authentication-plugin=mysql_native_password

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper

  order-service:
    build: order-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  tailing-service:
    build: tailing-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - kafka
      - order-service

  subscribe-service:
    build: subscribe-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - tailing-service
      - order-service