server:
  shutdown: graceful
  port: 8080

spring:
  r2dbc:
    username: root
    password: root
    url: mysql://localhost:3306/murloc?characterEncoding=UTF-8&useSSL=false

---
spring:
  config:
    activate:
      on-profile: docker
  r2dbc:
    url: mysql://mysql:3306/murloc?characterEncoding=UTF-8&useSSL=false

kafka:
  bootstrapAddress: kafka:9092